### ISSUE TITLE
problem when run mpe environment again after transform datasets

### ISSUE THREAD

**Issue by yycloudywind** [zbzhu99/madiff#10]
Dr.Zhu:
I previously downloaded and successfully ran the **mpe** environment, but after downloading the **mamujoco** and **smac** environments today and running `transform_og_marl_dataset.py` with the **mamujoco** dataset, I encountered the following error when trying to rerun the **mpe** environment:
```
Traceback (most recent call last):
  File "run_scripts/train.py", line 261, in <module>
    main(Config, RUN)
  File "run_scripts/train.py", line 85, in main
    dataset = dataset_config()
  File "~/madiff/diffuser/utils/config.py", line 66, in __call__
    instance = self._class(*args, **kwargs, **self._dict)
  File "~/madiff/diffuser/datasets/sequence.py", line 104, in __init__
    for _, episode in enumerate(itr):
  File "~/madiff/diffuser/datasets/mpe.py", line 169, in sequence_dataset
    n_agents = env.n
AttributeError: 'StackWrapper' object has no attribute 'n'
```
The StackWrapper class was able to set without any issues before. However, after running the new environments and dataset, this error appears when I attempt to run the mpe environment again.

**Comment by yycloudywind** [comment]
ok, this issue happened for the reason that i had change the version of gym, in lower version of gym, env in class wrapper is an attribute, while in recent version we can access env through inheritance
