### ISSUE TITLE
Missing MuJoCo Error When Starting Training for MPE

### ISSUE THREAD

**Issue by blablabLACK** [zbzhu99/madiff#9]
Something went wrong when I started training `mad_mpe_spread_attn_exp`. The error is related to missing MuJoCo.
I successfully installed the requirements using requirements.txt, and before training, I ran 
`pip install -e third_party/multiagent-particle-envs`
`pip install -e third_party/ddpg-agent`
and
`pip install -e third_party/multiagent_mujoco`
Additionally, I have MuJoCo packages in my conda environment, specifically MuJoCo 2.3.0 and mujoco-py 2.1.2.14. The environment seems correct. 
Could you provide some advice to address this problem? Thank you very much!
The error log is as follows:
```
Warning: Gym version v0.24.1 has a number of critical issues with `gym.make` such that environment observation and action spaces are incorrectly evaluated, raising incorrect errors and warning . It is recommend to downgrading to v0.23.1 or upgrading to v0.25.1
[ utils/colab ] Warning: not importing colab dependencies
/opt/conda/envs/madiff/lib/python3.8/site-packages/Cython/Distutils/old_build_ext.py:15: DeprecationWarning: dep_util is Deprecated. Use functions from setuptools instead.
  from distutils.dep_util import newer, newer_group

You appear to be missing MuJoCo.  We expected to find the file here: /root/.mujoco/mujoco210

This package only provides python bindings, the library must be installed separately.

Please follow the instructions on the README to install MuJoCo

    https://github.com/openai/mujoco-py#install-mujoco

Which can be downloaded from the website

    https://www.roboti.us/index.html

Traceback (most recent call last):
  File "run_experiment.py", line 10, in <module>
    from diffuser.utils.launcher_util import RUN, build_nested_variant_generator
  File "/data/users/yy/projects/madiff/diffuser/utils/__init__.py", line 8, in <module>
    from .mahalfcheetah_rendering import MAHalfCheetahRenderer
  File "/data/users/yy/projects/madiff/diffuser/utils/mahalfcheetah_rendering.py", line 6, in <module>
    import mujoco_py as mjc
  File "/opt/conda/envs/madiff/lib/python3.8/site-packages/mujoco_py/__init__.py", line 2, in <module>
    from mujoco_py.builder import cymj, ignore_mujoco_warnings, functions, MujocoException
  File "/opt/conda/envs/madiff/lib/python3.8/site-packages/mujoco_py/builder.py", line 503, in <module>
    mujoco_path = discover_mujoco()
  File "/opt/conda/envs/madiff/lib/python3.8/site-packages/mujoco_py/utils.py", line 78, in discover_mujoco
    raise Exception(message)
Exception: 
You appear to be missing MuJoCo.  We expected to find the file here: /root/.mujoco/mujoco210

This package only provides python bindings, the library must be installed separately.

Please follow the instructions on the README to install MuJoCo

    https://github.com/openai/mujoco-py#install-mujoco

Which can be downloaded from the website

    https://www.roboti.us/index.html
```
And here is my conda list:
```
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
_openmp_mutex             4.5                       2_gnu    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
absl-py                   2.1.0                    pypi_0    pypi
aiofile                   3.9.0                    pypi_0    pypi
aiofiles                  24.1.0                   pypi_0    pypi
argcomplete               3.5.1                    pypi_0    pypi
argparse                  1.4.0                    pypi_0    pypi
atomicwrites              1.4.1                    pypi_0    pypi
attrs                     24.2.0                   pypi_0    pypi
black                     23.1.0                   pypi_0    pypi
boto3                     1.35.65                  pypi_0    pypi
botocore                  1.35.65                  pypi_0    pypi
bracex                    2.5.post1                pypi_0    pypi
bzip2                     1.0.8                h4bc722e_7    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
ca-certificates           2024.8.30            hbcca054_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
cachetools                4.2.4                    pypi_0    pypi
caio                      0.9.17                   pypi_0    pypi
certifi                   2024.8.30                pypi_0    pypi
cffi                      1.17.1                   pypi_0    pypi
charset-normalizer        3.4.0                    pypi_0    pypi
click                     8.1.7                    pypi_0    pypi
cloudpickle               1.3.0                    pypi_0    pypi
contourpy                 1.1.1                    pypi_0    pypi
cycler                    0.12.1                   pypi_0    pypi
cython                    0.29.21                  pypi_0    pypi
d4rl                      1.1                      pypi_0    pypi
ddpg-agent                0.0.1                     dev_0    <develop>
deepdiff                  8.0.1                    pypi_0    pypi
diffusers                 0.24.0                   pypi_0    pypi
dill                      0.3.9                    pypi_0    pypi
dm-control                1.0.8                    pypi_0    pypi
dm-env                    1.6                      pypi_0    pypi
dm-tree                   0.1.8                    pypi_0    pypi
einops                    0.8.0                    pypi_0    pypi
enum34                    1.1.10                   pypi_0    pypi
expandvars                0.12.0                   pypi_0    pypi
fasteners                 0.19                     pypi_0    pypi
filelock                  3.16.1                   pypi_0    pypi
fonttools                 4.55.0                   pypi_0    pypi
fsspec                    2024.10.0                pypi_0    pypi
functional-notations      0.5.2                    pypi_0    pypi
future                    1.0.0                    pypi_0    pypi
gitdb                     4.0.5                    pypi_0    pypi
gitpython                 3.1.9                    pypi_0    pypi
glfw                      1.12.0                   pypi_0    pypi
google-auth               1.35.0                   pypi_0    pypi
google-auth-oauthlib      0.4.6                    pypi_0    pypi
grpcio                    1.68.0                   pypi_0    pypi
gtimer                    1.0.0b5                  pypi_0    pypi
gym                       0.24.1                   pypi_0    pypi
gym-notices               0.0.8                    pypi_0    pypi
gymnasium                 0.27.1                   pypi_0    pypi
gymnasium-notices         0.0.1                    pypi_0    pypi
h5py                      3.11.0                   pypi_0    pypi
html5tagger               1.3.0                    pypi_0    pypi
httptools                 0.6.4                    pypi_0    pypi
huggingface-hub           0.26.2                   pypi_0    pypi
idna                      3.10                     pypi_0    pypi
imageio                   2.35.1                   pypi_0    pypi
imageio-ffmpeg            0.5.1                    pypi_0    pypi
importlib-metadata        8.5.0                    pypi_0    pypi
isort                     5.12.0                   pypi_0    pypi
jax-jumpy                 1.0.0                    pypi_0    pypi
jaynes                    0.8.11                   pypi_0    pypi
jmespath                  1.0.1                    pypi_0    pypi
joblib                    0.16.0                   pypi_0    pypi
kiwisolver                1.4.7                    pypi_0    pypi
labmaze                   1.0.6                    pypi_0    pypi
ld_impl_linux-64          2.43                 h712a8e2_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libffi                    3.4.2                h7f98852_5    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libgcc                    14.2.0               h77fa898_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libgcc-ng                 14.2.0               h69a702a_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libgomp                   14.2.0               h77fa898_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libnsl                    2.0.1                hd590300_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libsqlite                 3.47.0               hadc24fc_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libuuid                   2.38.1               h0b41bf4_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libxcrypt                 4.4.36               hd590300_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libzlib                   1.3.1                hb9d3cd8_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
lxml                      5.3.0                    pypi_0    pypi
madiff                    0.0.0                     dev_0    <develop>
mamujoco                  0.0.0                     dev_0    <develop>
markdown                  3.7                      pypi_0    pypi
markupsafe                2.1.5                    pypi_0    pypi
matplotlib                3.6.3                    pypi_0    pypi
mjrl                      1.0.0                    pypi_0    pypi
ml-logger                 0.8.69                   pypi_0    pypi
mock                      5.1.0                    pypi_0    pypi
more-itertools            10.5.0                   pypi_0    pypi
mpyq                      0.2.5                    pypi_0    pypi
mujoco                    2.3.0                    pypi_0    pypi
mujoco-py                 2.1.2.14                 pypi_0    pypi
multiagent                0.0.1                     dev_0    <develop>
multidict                 6.1.0                    pypi_0    pypi
mypy-extensions           1.0.0                    pypi_0    pypi
ncurses                   6.5                  he02047a_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
networkx                  3.1                      pypi_0    pypi
numpy                     1.24.4                   pypi_0    pypi
numpy-stl                 2.17.1                   pypi_0    pypi
oauthlib                  3.2.2                    pypi_0    pypi
opencv-python             4.10.0.84                pypi_0    pypi
openssl                   3.4.0                hb9d3cd8_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
opt-einsum                3.1.0                    pypi_0    pypi
orderly-set               5.2.2                    pypi_0    pypi
packaging                 23.0                     pypi_0    pypi
pandas                    1.3.5                    pypi_0    pypi
params-proto              2.9.6                    pypi_0    pypi
path                      15.0.0                   pypi_0    pypi
pathspec                  0.12.1                   pypi_0    pypi
pillow                    10.4.0                   pypi_0    pypi
pip                       24.3.1             pyh8b19718_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
platformdirs              4.3.6                    pypi_0    pypi
pluggy                    1.5.0                    pypi_0    pypi
portpicker                1.6.0                    pypi_0    pypi
protobuf                  5.28.3                   pypi_0    pypi
psutil                    6.1.0                    pypi_0    pypi
py                        1.11.0                   pypi_0    pypi
pyasn1                    0.6.1                    pypi_0    pypi
pyasn1-modules            0.4.1                    pypi_0    pypi
pybullet                  3.2.6                    pypi_0    pypi
pycparser                 2.22                     pypi_0    pypi
pycurl                    7.45.3                   pypi_0    pypi
pygame                    2.6.1                    pypi_0    pypi
pyglet                    1.5.0                    pypi_0    pypi
pyopengl                  3.1.5                    pypi_0    pypi
pyparsing                 2.2.2                    pypi_0    pypi
pyrsistent                0.16.0                   pypi_0    pypi
pysc2                     3.0.0                    pypi_0    pypi
pytest                    3.8.2                    pypi_0    pypi
python                    3.8.20          h4a871b0_2_cpython    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
python-dateutil           2.7.3                    pypi_0    pypi
python-utils              2.4.0                    pypi_0    pypi
pytz                      2024.2                   pypi_0    pypi
pywavelets                1.4.1                    pypi_0    pypi
pyyaml                    6.0                      pypi_0    pypi
readline                  8.2                  h8228510_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
regex                     2024.11.6                pypi_0    pypi
requests                  2.32.3                   pypi_0    pypi
requests-futures          1.0.2                    pypi_0    pypi
requests-oauthlib         2.0.0                    pypi_0    pypi
requests-toolbelt         1.0.0                    pypi_0    pypi
rsa                       4.9                      pypi_0    pypi
ruamel-yaml               0.18.6                   pypi_0    pypi
ruamel-yaml-clib          0.2.8                    pypi_0    pypi
s2clientprotocol          5.0.13.92440.3           pypi_0    pypi
s2protocol                5.0.13.92440.4           pypi_0    pypi
s3transfer                0.10.3                   pypi_0    pypi
safetensors               0.4.5                    pypi_0    pypi
sanic                     24.6.0                   pypi_0    pypi
sanic-cors                2.2.0                    pypi_0    pypi
sanic-routing             23.12.0                  pypi_0    pypi
scikit-image              0.19.3                   pypi_0    pypi
scikit-video              1.1.11                   pypi_0    pypi
scipy                     1.10.1                   pypi_0    pypi
seaborn                   0.13.2                   pypi_0    pypi
setuptools                75.3.0             pyhd8ed1ab_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
six                       1.16.0                   pypi_0    pypi
sk-video                  1.1.10                   pypi_0    pypi
smmap                     3.0.5                    pypi_0    pypi
subprocess32              3.5.4                    pypi_0    pypi
tensorboard               2.0.2                    pypi_0    pypi
tensorboardx              2.0                      pypi_0    pypi
tensorflow-estimator      2.0.0                    pypi_0    pypi
termcolor                 2.4.0                    pypi_0    pypi
tifffile                  2023.7.10                pypi_0    pypi
tk                        8.6.13          noxft_h4845f30_101    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
tomli                     2.1.0                    pypi_0    pypi
torch                     1.12.1+cu113             pypi_0    pypi
tqdm                      4.67.0                   pypi_0    pypi
tracerite                 1.1.1                    pypi_0    pypi
typed-argument-parser     1.7.2                    pypi_0    pypi
typing                    3.7.4.3                  pypi_0    pypi
typing-extensions         4.12.2                   pypi_0    pypi
typing-inspect            0.9.0                    pypi_0    pypi
ujson                     5.10.0                   pypi_0    pypi
urllib3                   1.26.20                  pypi_0    pypi
uvloop                    0.21.0                   pypi_0    pypi
waterbear                 2.6.8                    pypi_0    pypi
wcmatch                   10.0                     pypi_0    pypi
websocket-client          1.8.0                    pypi_0    pypi
websockets                13.1                     pypi_0    pypi
werkzeug                  3.0.6                    pypi_0    pypi
wheel                     0.45.0             pyhd8ed1ab_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
whichcraft                0.6.1                    pypi_0    pypi
xz                        5.2.6                h166bdaf_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
zipp                      3.20.2                   pypi_0    pypi
```

**Comment by blablabLACK** [comment]
After installing mujoco210 in `/root/.mujoco/ `, the error was gone.

**Comment by zbzhu99** [comment]
Thank you for pointing out this! I will check it and update the installation instructions if necessary.
